### ISSUE TITLE
Error building this with docker,, 

### ISSUE THREAD

**Issue by ghost** [Mapotempo/docker-osrm-builder#1]
ERROR: pull access denied for mapotempo/postgis, repository does not exist or may require 'docker login'
after docker login i get this other error
error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

**Comment by frodrigo** [comment]
It's not published on repository. You must build it, it from postgis/Dockerfile.
`docker-compose buils` should build it.

**Comment by ghost** [comment]
Attaching to builder_builder_1
builder_1      | basename: invalid option -- 'p'
builder_1      | Try 'basename --help' for more information.
builder_1      | /usr/bin/entrypoint.sh: line 13: [: ==: unary operator expected
builder_1      | Build data.
builder_1      | docker-compose -p builder up --no-color builder
builder_1      | /usr/bin/entrypoint.sh: line 21: docker-compose: command not found
builder_builder_1 exited with code 127

**Comment by ghost** [comment]
ERROR: No such service: osrm--

**Comment by frodrigo** [comment]
Do you solve this issues ? how ?

**Comment by ghost** [comment]
Trying to rebuild osrm from scratch

**Comment by frodrigo** [comment]
We make a mistake in the last refactoring, I just fix it.
