### ISSUE TITLE
error getting this running

### ISSUE THREAD

**Issue by rodManuel** [Mapotempo/docker-osrm-builder#2]
it builds all fine, but it doesnt starts and says no such as osrm service

**Comment by frodrigo** [comment]
router-osrm-builder is just the data compiler.
The runtime is here: https://github.com/Mapotempo/router-wrapper

**Comment by rodManuel** [comment]
yeah but it cant run.. it says no osrm--service and later on the runtime cant load correctly profiles.. it is not clear

**Comment by alain-andre** [comment]
We close this issue. If it is related to the builder and not the router, reopen it.
